import type { Metadata } from "next";
import { Inter as GeistSans, JetBrains_Mono as GeistMono } from "next/font/google";
import "./globals.css";
import CookieBanner from "./components/CookieBanner";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Analytics from "./components/Analytics";
import ThirdPartyScripts from "./components/ThirdPartyScripts";
import { initializeServices } from "@/lib/startup";

const geistSans = GeistSans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = GeistMono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Contract Analyzer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Initialize services on server startup
  if (typeof window === 'undefined') {
    initializeServices().catch(console.error);
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <CookieBanner />
        <SpeedInsights />
        <Analytics />
        <ThirdPartyScripts />
      </body>
    </html>
  );
}
